## 1. Importing Libraries and Defining Corpus

In [20]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Download necessary NLTK data (if not already downloaded)
# Directly download stopwords and punkt without complex find checks
# nltk.download will check if already present
nltk.download('stopwords')
nltk.download('punkt') # This is the standard tokenizer resource

# Sample documents
documents = [
    "The quick brown fox jumps over the lazy dog",
    "The lazy dog barks loudly",
    "A quick brown cat runs fast",
    "Foxes are known for their cunning",
    "Dogs are loyal and friendly animals"
]

print("Original Documents:")
for i, doc in enumerate(documents):
    print(f"Document {i+1}: {doc}")

Original Documents:
Document 1: The quick brown fox jumps over the lazy dog
Document 2: The lazy dog barks loudly
Document 3: A quick brown cat runs fast
Document 4: Foxes are known for their cunning
Document 5: Dogs are loyal and friendly animals


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


## 2. Text Preprocessing

In [13]:
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

def preprocess_text(text):
    # Lowercasing
    text = text.lower()
    # Tokenization
    words = nltk.word_tokenize(text)
    # Remove stopwords and stemming
    words = [ps.stem(word) for word in words if word.isalnum() and word not in stop_words]
    return " ".join(words)

preprocessed_documents = [preprocess_text(doc) for doc in documents]

print("Preprocessed Documents:")
for i, doc in enumerate(preprocessed_documents):
    print(f"Document {i+1}: {doc}")

Preprocessed Documents:
Document 1: quick brown fox jump lazi dog
Document 2: lazi dog bark loudli
Document 3: quick brown cat run fast
Document 4: fox known cun
Document 5: dog loyal friendli anim


## 3. Bag-of-Words (BoW) Implementation

In [14]:
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(preprocessed_documents)

print("BoW Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nBoW Matrix (Document-Term Matrix):")
print(bow_matrix.toarray())

BoW Vocabulary:
['anim' 'bark' 'brown' 'cat' 'cun' 'dog' 'fast' 'fox' 'friendli' 'jump'
 'known' 'lazi' 'loudli' 'loyal' 'quick' 'run']

BoW Matrix (Document-Term Matrix):
[[0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0]
 [0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0]]


### BoW Cosine Similarity

In [15]:
bow_similarity = cosine_similarity(bow_matrix)

print("BoW Cosine Similarity Matrix:")
print(bow_similarity)

# Example: Similarity between Document 1 and Document 2
print(f"\nSimilarity between Document 1 and Document 2 (BoW): {bow_similarity[0, 1]:.4f}")

BoW Cosine Similarity Matrix:
[[1.         0.40824829 0.36514837 0.23570226 0.20412415]
 [0.40824829 1.         0.         0.         0.25      ]
 [0.36514837 0.         1.         0.         0.        ]
 [0.23570226 0.         0.         1.         0.        ]
 [0.20412415 0.25       0.         0.         1.        ]]

Similarity between Document 1 and Document 2 (BoW): 0.4082


## 4. TF-IDF (Term Frequency-Inverse Document Frequency) Implementation

In [16]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(preprocessed_documents)

print("TF-IDF Vocabulary:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())

TF-IDF Vocabulary:
['anim' 'bark' 'brown' 'cat' 'cun' 'dog' 'fast' 'fox' 'friendli' 'jump'
 'known' 'lazi' 'loudli' 'loyal' 'quick' 'run']

TF-IDF Matrix:
[[0.         0.         0.40079126 0.         0.         0.33269295
  0.         0.40079126 0.         0.49677044 0.         0.40079126
  0.         0.         0.40079126 0.        ]
 [0.         0.56801408 0.         0.         0.         0.38040565
  0.         0.         0.         0.         0.         0.45827018
  0.56801408 0.         0.         0.        ]
 [0.         0.         0.38898761 0.48214012 0.         0.
  0.48214012 0.         0.         0.         0.         0.
  0.         0.         0.38898761 0.48214012]
 [0.         0.         0.         0.         0.61418897 0.
  0.         0.49552379 0.         0.         0.61418897 0.
  0.         0.         0.         0.        ]
 [0.53849791 0.         0.         0.         0.         0.36063833
  0.         0.         0.53849791 0.         0.         0.
  0.         0.53

### TF-IDF Cosine Similarity

In [17]:
tfidf_similarity = cosine_similarity(tfidf_matrix)

print("TF-IDF Cosine Similarity Matrix:")
print(tfidf_similarity)

# Example: Similarity between Document 1 and Document 2
print(f"\nSimilarity between Document 1 and Document 2 (TF-IDF): {tfidf_similarity[0, 1]:.4f}")

TF-IDF Cosine Similarity Matrix:
[[1.         0.31022896 0.31180567 0.1986016  0.11998183]
 [0.31022896 1.         0.         0.         0.13718886]
 [0.31180567 0.         1.         0.         0.        ]
 [0.1986016  0.         0.         1.         0.        ]
 [0.11998183 0.13718886 0.         0.         1.        ]]

Similarity between Document 1 and Document 2 (TF-IDF): 0.3102


## 5. Comparison and Summary

In [18]:
print("Comparison of BoW and TF-IDF:")
print("------------------------------")

print("BoW Vocabulary Size:", len(vectorizer.get_feature_names_out()))
print("TF-IDF Vocabulary Size:", len(tfidf_vectorizer.get_feature_names_out()))

print(f"\nBoW Similarity (Doc 1 vs Doc 2): {bow_similarity[0, 1]:.4f}")
print(f"TF-IDF Similarity (Doc 1 vs Doc 2): {tfidf_similarity[0, 1]:.4f}")

print("\nKey Differences:")
print("1.  **BoW (CountVectorizer)**: Represents documents by the raw count of words. It treats each word as independent and does not account for the importance of words.")
print("2.  **TF-IDF (TfidfVectorizer)**: Considers not only the frequency of a word in a document (TF) but also how unique or important the word is across the entire corpus (IDF). This often leads to better representation for similarity tasks as it down-weights common words (like 'the', 'is') and up-weights rare, significant words.")

print("\nIn this example:")
print("Document 1: The quick brown fox jumps over the lazy dog")
print("Document 2: The lazy dog barks loudly")
print("TF-IDF gives a slightly lower similarity score than BoW. This could be due to TF-IDF's ability to downplay common words like 'the' and 'dog' which appear in both, focusing more on unique terms that truly differentiate the documents.")

Comparison of BoW and TF-IDF:
------------------------------
BoW Vocabulary Size: 16
TF-IDF Vocabulary Size: 16

BoW Similarity (Doc 1 vs Doc 2): 0.4082
TF-IDF Similarity (Doc 1 vs Doc 2): 0.3102

Key Differences:
1.  **BoW (CountVectorizer)**: Represents documents by the raw count of words. It treats each word as independent and does not account for the importance of words.
2.  **TF-IDF (TfidfVectorizer)**: Considers not only the frequency of a word in a document (TF) but also how unique or important the word is across the entire corpus (IDF). This often leads to better representation for similarity tasks as it down-weights common words (like 'the', 'is') and up-weights rare, significant words.

In this example:
Document 1: The quick brown fox jumps over the lazy dog
Document 2: The lazy dog barks loudly
TF-IDF gives a slightly lower similarity score than BoW. This could be due to TF-IDF's ability to downplay common words like 'the' and 'dog' which appear in both, focusing more on uni